### ISSUE TITLE
Add link to DECIPHER to gene page

### ISSUE THREAD

**Issue by nawatts** [macarthur-lab/gnomadjs#154]
Requested by @anneodonnell

**Comment by nawatts** [comment]
In the current browser, there are links to several external references:

<img width="500" alt="screen shot 2018-08-03 at 11 57 59 am" src="https://user-images.githubusercontent.com/1156625/43652893-803ab8ba-9714-11e8-87ab-ab3c978d4d06.png">

gnomad-beta currently has links to Ensembl, UCSC, GeneCards, and OMIM. Should we add the rest of the links along with DECIPHER?

**Comment by anneodonnell** [comment]
DECIPHER link doesn't go to quite the right page - it's close though. It goes to : 

https://decipher.sanger.ac.uk/gene/ENSG00000169174#overview/clinical-info

And I'd like it to go to: 
https://decipher.sanger.ac.uk/gene/ENSG00000169174#overview/protein-info
That's the page with the protein view with domains and gnomAD data

**Comment by anneodonnell** [comment]
Also I think the new links look nice. I noticed this because I was using the DECIPHER link on the gnomAD page. Thanks!
