### ISSUE TITLE
Add MNVs to gnomAD browser

### ISSUE THREAD

**Issue by mattsolo1** [macarthur-lab/gnomadjs#195]
# Proposal for adding MNVs to gnomAD browser

*Note* that MNV (multi-nucleotide variant) is the new terminology going forward, rather than MNP (multi-nucleotide polymorphism).

## How ExAC browser handles MNPs

The file we use to flag MNVs in the exac browser is `MNPs_NotFiltered_ForBrowserRelease.txt.gz`: 

Each record looks like:

```
CHROM                                              10,10
SITES                                100010912,100010911
FILTER                                         PASS,PASS
REF                                                  C,T
REF_AF                             0.99998353,0.99998353
ALT                                                  A,A
ALT_AF                               1.647e-05,1.647e-05
FEATURE                  ENST00000260702,ENST00000260702
STRAND                                             -1,-1
CODONS                                   Gaa/Taa,gAa/gTa
COMBINED_CODON_CHANGE                            GAa/TTa
CATEGORY                                     RESCUED_LOF
LOF                                                  HC,
LOF_FILTER                                             ,
LOF_FLAGS                                              ,
QUESTIONABLE_PHASING                         False,False
NSAMPS                                                 2
AVG_DEPTH                                          46.98
MQ                                                 59.55
CONSEQUENCE                                  INT_CHANGED
Name: 0, dtype: object
```

The MNP sites are comma delimited.

In this example:

10-100010912-C-A results in a codon change to Gaa (Glu) --> Taa (Stop).
10-100010911-T-A results in a codon change to gAa (Glu) --> gTa (Val).

The combined effect of the two mutations: a codon change to GAa (Glu) --> TTa (Leu).

You can view these variants on the gene page for LOXL4 (http://exac.broadinstitute.org/gene/ENSG00000138131)

![image](https://user-images.githubusercontent.com/8867295/44490257-ddcffc80-a62b-11e8-8895-5392c47b21b7.png)

They are flagged as `MNP`, however the annotations have not changed.

Variant page... a warning is produced, but the consequence of the MNP is not visible (Glu --> Leu). Instead, still appears as Glu --> Ter

![image](https://user-images.githubusercontent.com/8867295/44490291-f5a78080-a62b-11e8-891e-2b7df82b4a53.png)

Records are prepared for our database using this function in `parsing.py`:

https://github.com/konradjk/exac_browser/blob/a212465c5b75752abe8990cf6aa581295835ab58/parsing.py#L150

```
def get_mnp_data(mnp_file):
    header = mnp_file.readline().strip().split('\t')
    for line in mnp_file:
        data = dict(zip(header, line.split('\t')))
        if any(map(lambda x: x == 'True', data['QUESTIONABLE_PHASING'])): continue
        chroms = data['CHROM'].split(',')
        chrom = chroms[0]
        sites = data['SITES'].split(',')
        refs = data['REF'].split(',')
        alts = data['ALT'].split(',')
        for i, site in enumerate(sites):
            all_sites = zip(chroms, sites, refs, alts)
            all_sites.remove(all_sites[i])
            mnp = {}
            mnp['xpos'] = get_xpos(chrom, site)
            mnp['ref'] = refs[i]
            mnp['alt'] = alts[i]
            mnp['site2'] = '-'.join(all_sites[0])
            if len(all_sites) > 1:
                mnp['site3'] = all_sites[1]
            mnp['combined_codon_change'] = data['COMBINED_CODON_CHANGE']
            mnp['category'] = data['CATEGORY']
            mnp['number_samples'] = data['NSAMPS']
            yield mnp
```

Which yields:

```
{'category': 'RESCUED_LOF', 'xpos': 10100010912, 'site2': '10-100010911-T-A', 'number_samples': '2', 'combined_codon_change': 'GAa/TTa', 'alt': 'A', 'ref': 'C'}
```

Variant records are retrieved and modified with a `has_mnp` flag, and the mnp data:

https://github.com/konradjk/exac_browser/blob/a212465c5b75752abe8990cf6aa581295835ab58/exac.py#L200

```
def load_mnps():
    db = get_db()
    start_time = time.time()

    db.variants.ensure_index('has_mnp')
    print 'Done indexing.'
    while db.variants.find_and_modify({'has_mnp' : True}, {'$unset': {'has_mnp': '', 'mnps': ''}}):
        pass
    print 'Deleted MNP data.'

    with gzip.open(app.config['MNP_FILE']) as mnp_file:
        for mnp in get_mnp_data(mnp_file):
            variant = lookups.get_raw_variant(db, mnp['xpos'], mnp['ref'], mnp['alt'], True)
            db.variants.find_and_modify({'_id': variant['_id']}, {'$set': {'has_mnp': True}, '$push': {'mnps': mnp}}, w=0)

    db.variants.ensure_index('has_mnp')
    print 'Done loading MNP info. Took %s seconds' % int(time.time() - start_time)
```

## How do we treat MNVs in gnomAD browser?

+ Display MNV analysis result on gene/variant pages (LoF rescue, etc).
+ Display exact codon changes and updated functional interpretation on variant page.
+ Site variants where 100% of samples actually comprise MNVs make the VEP annotation at the site variants misleading -- should these be filtered? 
+ How to represent MNV effect across transcripts? (the residue numbers will change)
+ Add LC LoF flag (Anne suggested)
+ Should MNVs have a special variant ID of some sort and treated as a new variant record?
+ The file format that Qingbo provides will depend on the above questions. 
+ We will need a hail script that annotates variants with the MNV data for our hail variant loading pipeline (Nick?).

**Comment by nawatts** [comment]
MNV file: https://macarthurlab.slack.com/archives/C02A348ML/p1540327142000100

**Comment by nawatts** [comment]
Relevant commits:
* e5bb5e7fc7ba1ffa707f5c4d3ba514a9a258cd1d
* 7237ad04b4cd70b8aad3b0495422775d40d42115
* 42349b74b46801edc11fa2684550cebe1631c9fc
* d7daa14ad0e149a6515df0386b58740961a2f842
* 71f23977f801c3f450d0f557e50674fac564eb31
* 5bf4f7a135bc513446db9e8c354ca5aaaaaa8dc8
* 45efa6ce54703965a67856700c919edc9a03a2ee
