### ISSUE TITLE
HGNC approved gene symbols

### ISSUE THREAD

**Issue by bryonyt** [macarthur-lab/gnomadjs#224]
It would be very helpful for sequence variant interpretation purposes if gnomAD used the HGNC approved gene symbols in the browser. Below are two examples where an old gene alias is used instead of the HGNC approved symbol:
ADA2 is reported as CECR1 - http://gnomad-beta.broadinstitute.org/gene/CECR1
TWNK is reported as C10orf2 - http://gnomad-beta.broadinstitute.org/gene/C10orf2

**Comment by nawatts** [comment]
The gene symbols displayed come from Gencode version 19. Future versions of gnomAD may use a more recent version of Gencode.
