### ISSUE TITLE
Distinguishing ClinVar variants in gnomAD

### ISSUE THREAD

**Issue by anneodonnell** [macarthur-lab/gnomadjs#243]
Adding ability to only see ClinVar variants that are present in gnomAD - and easily evaluate allele frequency of these variants in gnomAD. 

On the ClinGen SVI (sequence variant interpretation) call today - which was a small subgroup meeting - Steven Harrison and I showed the new gnomAD ClinVar data and missense constraint. One comment was that diagnostic labs look up which ClinVar variants are actually in gnomAD and the allele frequencies so it would be super useful from their perspective if you could also only view the ClinVar variants in gnomAD and see their allele frequencies (probably in the hover over information). Would it be possible to add a check box to only see ClinVar variants that are present in gnomAD?

**Comment by nawatts** [comment]
@anneodonnell the ClinVar VCF file has 3 allele frequency fields: from GO-ESP, ExAC, and TGB. Is one of those preferred? Or should they all be displayed?
