### ISSUE TITLE
Consequence filters on multiple lines

### ISSUE THREAD

**Issue by mattsolo1** [macarthur-lab/gnomadjs#282]
Didn’t notice this earlier but PR #277 appears to have caused the consequence filters and help topic icon to display on multiple lines at 100% zoom and full screen width, 15" mbp. 

![image](https://user-images.githubusercontent.com/8867295/46690264-d65eb580-cbcf-11e8-84ad-6d84f3d49a62.png)

**Comment by nawatts** [comment]
I'm not seeing that at default resolution/full screen width (also on a 15" MBP).

<img width="1792" alt="screen shot 2018-10-09 at 2 36 46 pm" src="https://user-images.githubusercontent.com/1156625/46690620-ce534580-cbd0-11e8-93f2-bb24a28b2cc4.png">

But there is a range of window widths where the styles on the filter settings section causes this component to wrap.
