### ISSUE TITLE
Add SNP and indel filters

### ISSUE THREAD

**Issue by nawatts** [macarthur-lab/gnomadjs#288]
SNP: ref.length == alt.length == 1
indel: ref.length != alt.length

**Comment by knguyen142** [comment]
What are the conditions for the filter? I have the boilerplate here https://github.com/macarthur-lab/gnomadjs/compare/kev/indel-snp-filters?expand=1#diff-d879a2b4d644107278b72ecca9a0a1ecR399 

and tried looking at the variant data to get the condition but couldn't.

Sample variant:
1-55505447-C-T:
allele_count: 2846
allele_freq: 0.09068315065001274
allele_num: 31384
consequence: "5_prime_UTR_variant"
datasets: ["gnomadGenomeVariants"]
filters: []
flags: []
hemi_count: 0
hgvs: "c.-64C>T"
hgvsc: "c.-64C>T"
hgvsp: null
hom_count: 144
id: "1-55505447-C-T"
isCanon: true
populations: (8) [{…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}]
pos: 55505447
rsid: "rs45448095"
variant_id: "1-55505447-C-T"
xpos: 1055505447

**Comment by knguyen142** [comment]
Also, do indels and snps need the question mark icon with help expansion?

**Comment by nawatts** [comment]
You can extract ref and alt from the variant ID. The format of the variant ID is `chromosome number - position - reference allele - alternate allele`.

Don't worry about help information for these filters now, we can add that later if needed.
