### ISSUE TITLE
Support searching for variants by rsID

### ISSUE THREAD

**Issue by nawatts** [macarthur-lab/gnomadjs#302]

**Comment by gymreklab** [comment]
Adding to this issue, if I type an rsID into the search bar, the dropdown box appears to be broken. Pressing Enter doesn't seem to work.

**Comment by nawatts** [comment]
If there are no results for a search query, the dropdown box shows no content. #313 tracks clarifying when there are no results for a query.

**Comment by nawatts** [comment]
Support for searching by rsID added in c8155bc8142772011117719fd27d35a38c750192.
