### ISSUE TITLE
Table of Functional Gene Constraint for non-neuro cohort with new pLI and OE values

### ISSUE THREAD

**Issue by dantaki** [macarthur-lab/gnomadjs#307]
I found this table: https://storage.googleapis.com/gnomad-public/release/2.1/ht/constraint/constraint.txt.bgz 

But would like the same information for the non-neuro cohort. Can you please provide that please? 

Thank you.

**Comment by nawatts** [comment]
Hi @dantaki. Gene constraint data for subsets of gnomAD is not currently available. It may be in the future, but for most genes it is not expected to significantly differ from gene constraint for the full dataset.

**Comment by dantaki** [comment]
Thanks for the quick response. I would like to stress the importance of providing the non-psych data, which has been a vital resource for the psychiatric genomics field.
