### ISSUE TITLE
Export/save coverage plot and exon schematic

### ISSUE THREAD

**Issue by mebbert** [macarthur-lab/gnomadjs#330]
Hi,

The previous versions of gnomAD had a way to save/export the coverage plot and exon schematic, but I don't see how to do that in 2.1. Is that feature coming? We'd like to include several images in an upcoming publication.

Really appreciate it.

**Comment by mebbert** [comment]
A ton of nice improvement, overall, BTW. Nice work.

**Comment by nawatts** [comment]
Hi @mebbert 

Thanks for the feedback. Yes, we do plan on adding that feature to the new browser (tracked in #226).

**Comment by mebbert** [comment]
Wonderful. Do you have an estimated timeframe? Trying to decide if I should stick with the older version for our paper.

**Comment by mebbert** [comment]
Hello,

Just curious if you have an estimate on when this feature will be implemented. Really appreciate it.

**Comment by nawatts** [comment]
I don't have a specific timeframe, but I do expect to have this done some time in December.

**Comment by nawatts** [comment]
Saving these two plots to SVG files is now available on http://gnomad.broadinstitute.org.
