### ISSUE TITLE
Variant Missing from Gene View

### ISSUE THREAD

**Issue by nathanmadams** [macarthur-lab/gnomadjs#351]
Why isn't http://gnomad.broadinstitute.org/variant/1-66089782-C-T included in the variant table for http://gnomad.broadinstitute.org/gene/ENSG00000116678/transcript/ENST00000349533 ?

-------------- 👆 Click "Preview"!

Instead of filing an issue on GitHub, please email questions about the
gnomAD or ExAC datasets to [exomeconsortium@gmail.com](mailto:exomeconsortium@gmail.com).

Answers to frequently asked questions may be found at http://gnomad-beta.broadinstitute.org/faq.

**Comment by nawatts** [comment]
Hi @nathanmadams,

The gene and transcript pages only show variants that fall in or within 75 bases of a CDS region in the gene or transcript. In this case, the variant at position 66089782 falls between two CDS regions located at positions 66088590-66088665 and 66101875-66102696.
