### ISSUE TITLE
search does not work 

### ISSUE THREAD

**Issue by NUHMolGen** [macarthur-lab/gnomadjs#355]
### What you did:
On gnomAD homepage the search feature is not working- typing a gene name or a region just brings up a "searching" box

### What happened:

![image](https://user-images.githubusercontent.com/40829205/48838942-ce269800-ed81-11e8-8797-f1be1c99e336.png)

**Comment by nawatts** [comment]
Hi @NUHMolGen,

I'm unable to reproduce this issue:

<img width="804" alt="screen shot 2018-11-21 at 7 52 38 am" src="https://user-images.githubusercontent.com/1156625/48842574-99efaf00-ed62-11e8-9260-82bb8e31a61c.png">

What browser are you using? Are you able to view data on other pages (example: http://gnomad-beta.broadinstitute.org/gene/PCSK9)?

**Comment by NUHMolGen** [comment]
It seems to be fixed now.
