### ISSUE TITLE
LoF LC for non-coding transcripts

### ISSUE THREAD

**Issue by konradjk** [macarthur-lab/gnomadjs#364]
Transferred from https://github.com/konradjk/loftee/issues/40 h/t @rvernica

For non-coding transcripts, the gnomAD browser is showing "low-confidence" annotations (e.g. http://gnomad.broadinstitute.org/variant/1-3782413-C-T). This is consistent with the ExAC browser (not a gnomAD-specific issue), but on reflection, it might not actually be the best display (LOFTEE did not assess this variant as it was on a non-coding transcript).

**Comment by konradjk** [comment]
Oof, one unambiguous thing to fix though: in this particular case, the gene is protein coding, but the transcript is not, so that definitely should be updated to say "non-protein coding transcript"

**Comment by nawatts** [comment]
This annotation is done in the Elasticsearch loading pipeline:
https://github.com/macarthur-lab/hail-elasticsearch-pipelines/blob/5aa63cdd4cfaae01c8d4ee9608440654fca60044/hail_scripts/v02/utils/computed_fields/vep.py#L218-L224

To match gnomad_browser's behavior in:
https://github.com/macarthur-lab/gnomad_browser/blob/b4ff2705fd540037acc31f234f660b26162f5207/utils.py#L79-L84

**Comment by nawatts** [comment]
@konradjk was "NC" something made up for gnomad_browser? Or will LOFTEE use that annotation in other circumstances? If "NC" doesn't appear otherwise, we can change how the browser renders that annotation.

**Comment by konradjk** [comment]
It was made up, yes, for convenience. Not saying LOFTEE will never use that, but it certainly doesn't at this time and no plans to

**Comment by nawatts** [comment]
> Not saying LOFTEE will never use that, but it certainly doesn't at this time and no plans to

Since we'll have to reload all variants for gnomAD 2.1.1, we can remove it from the loading pipeline before then and won't have to worry about it after that. Since that's the only case where it is added, we can change the browser's behavior now. What should the browser show in these cases?

**Comment by nawatts** [comment]
On the variant page, transcript consequences with a VEP annotation of frameshift or more severe but no LOFTEE annotation will be marked "LoF: Low-confidence (Non-protein-coding transcript)".

If such a consequence is the one shown for a variant on the gene or region page, then the variant should have a "NC Transcript" flag.
