### ISSUE TITLE
MAGEL2 gene inconsistencies

### ISSUE THREAD

**Issue by keziabrown** [macarthur-lab/gnomadjs#383]
### What you did: 
When looking for population data for the MAGEL2 c.2642G>A p.Arg881His variant, the information within gnomAD does not match up with the transcript information. Genomic coordinates (Build37) 23890248 matches to p.Arg278His instead, and the highest c. position entry is c.1940? Checked the transcript ID ENST00000532292 in Ensembl, which matches with NM_019066.4 and NP_061939.3 and ENST information we were provided for this variant. Checking in Alamut by c. position identifies p.Arg881His as the correct nomenclature and links to this p.Arg278His entry in gnomAD.
http://gnomad.broadinstitute.org/gene/ENSG00000254585
http://gnomad.broadinstitute.org/variant/15-23890248-C-T

Is the information for this gene entered correctly into gnomAD?

**Comment by nawatts** [comment]
The annotations in gnomAD are based on Gencode version 19 (http://grch37.ensembl.org/Homo_sapiens/Transcript/Summary?db=core;g=ENSG00000254585;r=15:23888691-23891175;t=ENST00000532292) and changes have been made to this transcript in more recent versions. We will be updating to a more recent Gencode version in a future release.
