### ISSUE TITLE
ImportError: cannot import name 'get_expr_for_original_alt_alleles_set'

### ISSUE THREAD

**Issue by Jack-Ow** [macarthur-lab/gnomadjs#385]
### What you did:
Started an AWS EMR with Spark version 2.3.2 and installed hail 0.2 with this help.  
https://github.com/hms-dbmi/hail-on-EMR

Ran the following 
spark-submit \
  --jars "$HAIL_HOME/build/libs/hail-all-spark.jar" \
  --py-files "$HAIL_HOME/build/distributions/hail-python.zip" \
  --conf spark.driver.extraClassPath="$HAIL_HOME/build/libs/hail-all-spark.jar" \
  --conf spark.executor.extraClassPath=./hail-all-spark.jar \
  --conf spark.serializer=org.apache.spark.serializer.KryoSerializer \
  --conf spark.kryo.registrator=is.hail.kryo.HailKryoRegistrator \
  /opt/gnomadjs/projects/gnomad/data/export_exac_vcf_to_htl.py
  

https://github.com/macarthur-lab/gnomadjs/blob/master/projects/gnomad/data/export_exac_vcf_to_ht.py

**Comment by Jack-Ow** [comment]
Encounter this error message :
 File "/opt/gnomadjs/projects/gnomad/data/export_exac_vcf_to_htl.py", line 21, in <module>
    from hail_scripts.v02.utils.computed_fields import (
ImportError: cannot import name 'get_expr_for_original_alt_alleles_set'

**Comment by Jack-Ow** [comment]
Hi,
Thanks for the quick response. Still encounter the same error. All the modules are in hail_scripts.v02.utils.computed_fields except get_expr_for_original_alt_alleles_set. 

from hail_scripts.v02.utils.computed_fields import (
    CONSEQUENCE_TERM_RANK_LOOKUP,
    get_expr_for_alt_allele,
    get_expr_for_contig,
    get_expr_for_lc_lof_flag,
    get_expr_for_loftee_flag_flag,
    **get_expr_for_original_alt_alleles_set**,
    get_expr_for_ref_allele,
    get_expr_for_start_pos,
    get_expr_for_variant_id,
    get_expr_for_vep_sorted_transcript_consequences_array,
    get_expr_for_xpos,
)

**Comment by nawatts** [comment]
Ah, that function was changed and renamed in hail-elasticsearch-pipelines. I'll work on getting the `hail-elasticsearch-pipelines` submodule pinned to a working version.

In the meantime, you can use this implementation of `get_expr_for_original_alt_alleles_set`:
```python
def get_expr_for_original_alt_alleles_set(split_variant):
    """Compute variant id for each original alt allele in a variant split with hl.split_multi"""
    return hl.set(
        split_variant.old_alleles[1:].map(
            lambda alt: get_expr_for_variant_id(hl.min_rep(split_variant.old_locus, [split_variant.old_alleles[0], alt]))
        )
    )
```

**Comment by Jack-Ow** [comment]
Thanks !
