### ISSUE TITLE
Gene constraint link file is not the same as gnomAD webpage??

### ISSUE THREAD

**Issue by klausSchmitz** [macarthur-lab/gnomadjs#405]
Dear gnomAD:

I am updating some databases for Manton Center at Childen Hospital and I noted that the file you can download for the "Gene constraint” is not the same as gnomAD webpage. The values change in small amounts. I am wondering which one of the files is the correct?

Example, the first gene (A1BG)
obs_lof= 14 or 8. In the gnomAD is 15. Pvalues are different as well.

Thank you, looking forward to know the true.

Klaus Schmitz Abe

**Comment by nawatts** [comment]
Hi @klausSchmitz 

The link on the downloads page was out of date. The data shown in the browser was from an updated version of the constraint dataset. The downloads page has now been updated with the latest files.

* Hail Table gs://gnomad-public/release/2.1.1/constraint/gnomad.v2.1.1.lof_metrics.by_transcript.ht
* TSV https://storage.googleapis.com/gnomad-public/release/2.1.1/constraint/gnomad.v2.1.1.lof_metrics.by_transcript.txt.bgz

**Comment by klausSchmitz** [comment]
Thank you so much, the new file works perfect.
klaus
