### ISSUE TITLE
SV variants BND: CHROM1:POS1/CHROM2:**POS1** is displayed 

### ISSUE THREAD

**Issue by lindenb** [macarthur-lab/gnomadjs#423]
when looking at the **BND** structural variants, the POS1 is used as the POS2:
e.g.

https://gnomad.broadinstitute.org/variant/BND_1_13?dataset=gnomad_sv_r2 

https://gnomad.broadinstitute.org/variant/BND_1_21?dataset=gnomad_sv_r2 

https://gnomad.broadinstitute.org/variant/BND_1_31?dataset=gnomad_sv_r2

for the position: the notation CHROM1:POS1|CHROM2:**POS1** is used instead of something like CHROM1:POS1|CHROM2:**POS2**
 
![image](https://user-images.githubusercontent.com/33838/60091653-6b491500-9745-11e9-850c-511120589366.png)

**Comment by nawatts** [comment]
As @RCollins13 said, the browser does display position links for BND structural variants as `chr:pos - chr2:end`.

https://github.com/macarthur-lab/gnomadjs/blob/0fc1abf11dddb56742c80803021277db476c214b/projects/gnomad/src/client/StructuralVariantPage/StructuralVariantAttributeList.js#L59-L71

https://github.com/macarthur-lab/gnomadjs/blob/0fc1abf11dddb56742c80803021277db476c214b/projects/gnomad/data/prepare_gnomad_svs_for_browser.py#L76-L77
