### ISSUE TITLE
gnomAD and ExAC pLI scores

### ISSUE THREAD

**Issue by eldee9** [macarthur-lab/gnomadjs#430]
I do not understand the discrepancy in pLI scores between GnomAD and ExAC datasets. For example, the pLI score for NBEAL2 gene in ExAC is 0,86, however, when you switch to GnomAD, it shows the value of pLI=0,06. What is the source data for GnomAD pLI? 
(btw, o/e for NBEAL2 is quite low 0,18-0,32, so it actually contradicts the value of pLI=0,06)

**Comment by konradjk** [comment]
This is a legitimate difference in the calculations of pLI and o/e (and correspondingly, LOEUF). pLI compute the probability that a gene is in the most constrained category ("haploinsufficient-looking", or about ~11% o/e). At 17 obs, 81 expected, the o/e was ~20%, but still a wider confidence interval around it, so it put it in the medium-high pLI category. Now with a larger sample size, 31/131 puts it squarely at ~25% with a pretty tight confidence interval. It's certainly very constrained but no longer confidently in that haploinsufficient category (which makes sense as there are at least 31 observed pLoFs).

It's a limitation of the pLI computation that the value can change drastically when it's in that 0.1-0.9 regime (whereas <0.1 and >0.9 are quite a bit more stable). o/e (and LOEUF, the upper bound of the o/e confidence interval) is much more stable, as you can see between the two callsets.
