### ISSUE TITLE
Render error on /gene/ENSG00000112144

### ISSUE THREAD

**Issue by shvetaj** [macarthur-lab/gnomadjs#481]
hello,
       On searching for the gene ICK in the epi25K genome browser. the page did not load.
the page said 'something went wrong', 'An error occurred while rendering this page' and 'This is a bug. Please file an issue on GitHub and reload the browser.'
Kindly look into the matter
-Shveta

**Comment by nawatts** [comment]
Hi @shvetaj,

Thanks for reporting this. I will look into it.

**Comment by nawatts** [comment]
http://epi25.broadinstitute.org/gene/ICK should render correctly row.

The problem was due to ICK not having an overall p value for the gene result. That was an edge case that the browser did not handle.
