### ISSUE TITLE
Gene data search function - Error

### ISSUE THREAD

**Issue by AberdeenMedGen** [macarthur-lab/gnomadjs#483]
Genes we used gnomAD regularly for e.g. TP53 and LPL are not appearing on the dropdown and there is no data when just searching and pressing enter. May be a version issue - first noticed 13/09/2019. 

Screenshots: 
![image](https://user-images.githubusercontent.com/55392388/64957922-e540f400-d885-11e9-9778-8981d20fb80b.png)
![image](https://user-images.githubusercontent.com/55392388/64957941-ef62f280-d885-11e9-8d1c-347ea424c3bf.png)

**Comment by nawatts** [comment]
Hi @AberdeenMedGen,

Searching for a gene should now always return the exact match (if there is one) first.

Also, you can navigate directly to a gene page by putting the gene name in the URL. For example, https://gnomad.broadinstitute.org/gene/TP53.
