### ISSUE TITLE
Is it coverage files missing from gnomAD v.3?

### ISSUE THREAD

**Issue by frequena** [macarthur-lab/gnomadjs#495]
Like the previous versions, I was expecting to be able to download the coverage files from the gnomAD v.3, but they are not available in this new version.

**Comment by nawatts** [comment]
Hi @frequena,

We are planning to release the coverage data for gnomAD v3. Those files should be available some time next week.

**Comment by frequena** [comment]
Thank you very much!

**Comment by nawatts** [comment]
The coverage files for gnomAD v3 are now listed on https://gnomad.broadinstitute.org/downloads.
