### ISSUE TITLE
Add note to quality metrics graphs

### ISSUE THREAD

**Issue by nawatts** [macarthur-lab/gnomadjs#511]
Add note to genotype quality, depth, and allele balance plots: “Plot may include low-quality genotypes that were excluded from allele counts in the table above”.

Similar to the ExAC browser variant page:
![image](https://user-images.githubusercontent.com/1156625/67584995-ba677c80-f71c-11e9-9cab-e0889632a4b9.png)

An example of where this would help: https://gnomad.broadinstitute.org/variant/1-55505670-G-A?dataset=gnomad_r2_1

**Comment by nawatts** [comment]
@lfrancioli is this also true for gnomAD v3?

**Comment by lfrancioli** [comment]
yes!
