### ISSUE TITLE
gsutil ls example command static across gnomAD versions

### ISSUE THREAD

**Issue by akotlar** [macarthur-lab/gnomadjs#514]
Switching between download sections doesn't update `gsutil ls` example command. While not a bug, it is the first command a user sees, which means they first take in the wrong command, then need to search for the right command, when attempting to download the v2 liftover or v3 versions.

<img width="1185" alt="Screen Shot 2019-10-28 at 11 34 36 AM" src="https://user-images.githubusercontent.com/5543229/67692683-ee3dde80-f976-11e9-8b11-3570ff0f18ac.png">

It would be useful to list the top level gsutil ls command for the relevant bucket, and remove the static example.

(or ignore this :)). Thanks!

**Comment by nawatts** [comment]
Hi @akotlar,

Thanks for pointing this out. I've reworded the top section of the downloads page to remove anything specific to gnomAD v2 and changed the directory in the gsutil example to the top-level `gs://gnomad-public/release`.

**Comment by akotlar** [comment]
Looks good, thanks @nawatts!
