### ISSUE TITLE
Search box does not wait for new results after new input

### ISSUE THREAD

**Issue by nawatts** [macarthur-lab/gnomadjs#521]
Steps to reproduce:
* Type in "PCSK" in the gnomAD search box.
* Wait for search results to appear. The first result should be "PCSK1".
* Type "9" and press enter.

Expected behavior:
Search results for "PCSK9" are fetched and the first result is selected. The browser navigates to the gene page for PCSK9.

Actual behavior:
The first result of the current list is selected. The browser navigates to the gene page for PCSK1.

**Comment by huy-nguyen** [comment]
This is a classic race condition that benefits from using an Observable. Something like `switchMap` would solve your problem. Suppose `keydown$` is the stream of keydown events then something like this would work
```js
import {switchMap, map} from 'rxjs/operators'
const searchResult$ = keydown$.pipe(
  map(() => inputDOMElement.value),
  switchMap(searchTerm => getGraphQLResult(searchTerm),
);
```
where getGraphQLResult sends out an AJAX request for the search result for a given `searchTerm`.

**Comment by nawatts** [comment]
This one wasn't so much because of a race condition... the search box would ignore the result of any in progress requests when it made a new one. However, if it already had a list of results loaded, then pressing enter while a request was in progress would select from the existing list instead of waiting for the request to finish. The solution was to clear the list of results when the input changed.
