### ISSUE TITLE
Some genes not returning variants

### ISSUE THREAD

**Issue by nawatts** [macarthur-lab/gnomadjs#53]
> Moved from https://github.com/macarthur-lab/gnomad_browser/issues/96
> Originally created by @mattsolo1 on *Fri, 26 Jan 2018 15:46:54 GMT*

eg ACTN3 https://twitter.com/WillisCD/status/956540872753074179
CLN3

**Comment by nawatts** [comment]
> Moved from https://github.com/macarthur-lab/gnomad_browser/issues/96#issuecomment-384301882
> Originally created by @mattsolo1 on *Wed, 25 Apr 2018 14:13:42 GMT*

See: https://github.com/macarthur-lab/hail-elasticsearch-pipelines/issues/35

**Comment by nawatts** [comment]
There _are_ variants annotated for these genes, but they are not returned from the API. It's possible they may not be in one of the exon regions shown in the browser.

* CLN3
  * http://gnomad-beta.broadinstitute.org/gene/CLN3
  * http://elastic:9200/gnomad_exomes_202_37/variant/_search?q=geneIds:ENSG00000261832&pretty&size=0

* ACTN3
  * http://gnomad-beta.broadinstitute.org/gene/ACTN3
  * http://elastic:9200/gnomad_exomes_202_37/variant/_search?q=geneIds:ENSG00000248746&pretty&size=0

**Comment by nawatts** [comment]
The problem is that the API queries for variants by `geneId` instead of `geneIds`. 

https://github.com/macarthur-lab/gnomadjs/blob/ee61e3f159bc3aae136972920289ca5ab560d69f/packages/api/src/schema/types/elasticVariant.js#L345

This means that variants will only be shown for a gene if their worst consequence is in that gene.

**Comment by mattsolo1** [comment]
These genes are now loading gnomAD 2.1 variants.
