### ISSUE TITLE
Using Gnomad with local datasets

### ISSUE THREAD

**Issue by Wanda-Sankey** [macarthur-lab/gnomadjs#537]
I am interested in using a local copy of the Gnomad search engine for my local vcf datasets. Is there a way to do this by changing some references in the code? I am struggling because javascript is not my language of preference, so sorting through the documents becomes difficult.

**Comment by nawatts** [comment]
Hi @Wanda-Sankey,

It is possible. Some of the commits for adding gnomAD v3 data to the browser may be a useful starting point: 529bdb782330a504c5105de5c02ba0ad34c458ad, 260a80c0e05f8206c25b0035626e4d1a682a9727, c6e91cc1d154a620f90301a794017861e67fab2f.

Also, the gnomAD browser uses [Elasticsearch](https://www.elastic.co/products/elasticsearch) for its database. The scripts in the [data](https://github.com/macarthur-lab/gnomadjs/tree/master/data) folder use [Hail](https://hail.is) to format the gnomAD data and upload to an Elasticsearch cluster. However, there are [Elasticsearch clients](https://www.elastic.co/guide/en/elasticsearch/client/index.html) available for several languages.

We're also considering building some sort of template browser that would be easier to repurpose for a single variant dataset. If you would be willing to share a bit more information about how you would like to use the browser (either here or by emailing [exomeconsortium@gmail.com](mailto:exomeconsortium@gmail.com)), it would help inform that project.

**Comment by Wanda-Sankey** [comment]
So if one were to simply use SQL or a VCF parser (such as Tabix), do you think it would be worth my time to try to modify Gnomad programming, or to just start on a new project from scratch? I doubt use Elasticsearch is feasible in my project.

**Comment by nawatts** [comment]
It would still be possible to reuse parts of the [front end of the browser](https://github.com/macarthur-lab/gnomadjs/tree/master/projects/gnomad). But if you want to change the database and prefer not to use JS, then it's probably easier to entirely replace the [API piece](https://github.com/macarthur-lab/gnomadjs/tree/master/projects/gnomad-api). You could either implement a similar [GraphQL](https://graphql.org/) interface as the existing API or change the data fetching parts of the front end (look for uses of the [Query](https://github.com/macarthur-lab/gnomadjs/blob/master/projects/gnomad/src/client/Query.js) component).
