### ISSUE TITLE
Hail version for reading Genome coverage Hail Table (v3)

### ISSUE THREAD

**Issue by ikarus97** [macarthur-lab/gnomadjs#541]
Hi,

I tried to load genome coverage hail table (https://console.cloud.google.com/storage/gnomad-public/release/3.0/coverage) with Hail 0.2. 
`hl.read_table('/data/gnomad.genomes.r3.0.coverage.ht')`
or
`hl.read_matrix_table('/data/gnomad.genomes.r3.0.coverage.ht')`

And got the following error in both cases:

Hail version: 0.2.9-8588a25687af
Error summary: HailException: incompatible file format when reading: /data/gnomad.genomes.r3.0.coverage.ht  supported version: 1.0.0, found 1.2.0

Does this mean that the Hail table file was created in Hail 0.1?
Any plan to release table in Hail 0.2?

**Comment by nawatts** [comment]
Hi @ikarus97,

That number refers to the Hail file format version, not the Hail version. It means that the Hail table was written with a more recent version of Hail and the format is not understood by your version of Hail. I believe the v3 coverage table requires at least Hail version 0.2.24.

> Please note that forward compatibility should not be expected, especially relating to file formats: this means that it may not be possible to use an earlier version of Hail to read files written in a later version.
> -- https://hail.is/docs/0.2/change_log.html#what-stability-is-guaranteed
