### ISSUE TITLE
Exac Constraint data source not working/returning any data

### ISSUE THREAD

**Issue by preetisi** [macarthur-lab/gnomadjs#547]
Hi, 

We have been using Exac constraint API (http://exac.broadinstitute.org/api/constraint) as our data source for Locuszoom plot. But, that link hasn't been working and gives us 405 error and CORS error. Could you please give us the right updated constraint API for gnomad. 

Thanks!

Instead of filing an issue on GitHub, please email questions about the
gnomAD or ExAC datasets to [exomeconsortium@gmail.com](mailto:exomeconsortium@gmail.com).

Answers to frequently asked questions may be found at https://gnomad.broadinstitute.org/faq.

**Comment by nawatts** [comment]
Hi @preetisi,

The [ExAC browser](http://exac.broadinstitute.org/) was shut down in December.

The [gnomAD browser API](https://gnomad.broadinstitute.org/api) uses [GraphQL](https://graphql.org/). An example query for fetching ExAC constraint can be seen at:

https://gnomad.broadinstitute.org/api?query=%0Aquery%20ExacConstraint(%24gene_id%3A%20String!)%20%7B%0A%20%20gene(gene_id%3A%20%24gene_id%2C%20reference_genome%3A%20GRCh37)%20%7B%0A%20%20%20%20exac_constraint%20%7B%0A%20%20%20%20%20%20exp_syn%0A%20%20%20%20%20%20obs_syn%0A%20%20%20%20%20%20syn_z%0A%20%20%20%20%20%20exp_mis%0A%20%20%20%20%20%20obs_mis%0A%20%20%20%20%20%20mis_z%0A%20%20%20%20%20%20exp_lof%0A%20%20%20%20%20%20obs_lof%0A%20%20%20%20%20%20lof_z%0A%20%20%20%20%20%20pLI%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D&operationName=ExacConstraint&variables=%7B%0A%20%20%22gene_id%22%3A%20%22ENSG00000169174%22%0A%7D

However, note that the gnomAD browser API should be considered undocumented and is subject to change at any time.

Alternatively, the ExAC constraint data is available for download at https://gnomad.broadinstitute.org/downloads#exac-constraint.
