### ISSUE TITLE
Render error on /gene/ENSG00000123384

### ISSUE THREAD

**Issue by builtinbc** [macarthur-lab/gnomadjs#550]
### What you did: I clicked on HGVSp/c to sort the mutations by protein change
https://schema.broadinstitute.org/gene/ENSG00000123384

### What happened: I got an error page: "Something Went Wrong
An error occurred while rendering this page.

This is a bug. Please file an issue on GitHub and reload the browser."

**Comment by builtinbc** [comment]
I'm using Safari 13.0.5 on a Mac

**Comment by builtinbc** [comment]
This has happened before when browsing other genes

**Comment by nawatts** [comment]
Hi @builtinbc,

Thanks for the bug report. This should be fixed now.

This issue was introduced recently with some changes to that table column (269157843cdbbec9b7e140151819f9be2e3dc85f).
