### ISSUE TITLE
Cannot download 'All possible SNVs annotated TSV'

### ISSUE THREAD

**Issue by dioncst** [macarthur-lab/gnomadjs#558]
### What you did:
 
download 'All possible SNVs annotated TSV'

**Comment by dioncst** [comment]
No such object: gnomad-public/papers/2019-tx-annotation/pre_computed/all.possible.snvs.tx_annotated.022719.tsv.bgz

**Comment by nawatts** [comment]
Hi @dioncst,

That dataset is in the process of being updated and the downloads page linked to an old file. The new version should be available next week. In the meantime, I've removed the broken links from the downloads page.

**Comment by dioncst** [comment]
> Hi @dioncst,
> 
> That dataset is in the process of being updated and the downloads page linked to an old file. The new version should be available next week. In the meantime, I've removed the broken links from the downloads page.

Thank you for you reply~

**Comment by berylc** [comment]
Hi @dioncst you can fine the updated HT and tsv file in 
gs://gnomad-public/papers/2019-tx-annotation/pre_computed/

Let me know if there are any issues. Apologies for any disruption!

**Comment by nawatts** [comment]
The browser's downloads page has also been updated with the latest file URLs.

https://gnomad.broadinstitute.org/downloads#v2-pext
