### ISSUE TITLE
Add alternating chromosome color option + locus highlighting to manhattan plot

### ISSUE THREAD

**Issue by mattsolo1** [macarthur-lab/gnomadjs#84]
Currently plot generates random colors for each chromosome. 

![image](https://user-images.githubusercontent.com/8867295/41553160-e8263ae2-72fe-11e8-8104-ff5ca81d997e.png)

Create second option for alternating red/blue colors. 

![image](https://user-images.githubusercontent.com/8867295/41553078-b61ea6ce-72fe-11e8-9ec4-c8a27f149b93.png)

In addition, data points less than a new prop `significanceThreshold` (default to 5.0e-8) +/- a new prop `locusSize` (default to 5000 bp) option should highlight green as shown. Also, create a line on the y axis at the -log10P of `significanceThreshold`. Can probably create an option to hide the other yaxis lines/

**Comment by nawatts** [comment]
Alternating colors for chromosomes is now the default for the Manhattan plot and the `pointColor` prop allows for projects to set a different color for points over a significance threshold.
